# Generated by Django 5.1 on 2024-09-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
